env: dataproc
gcs_bucket: 'dataproc-staging-us-central1-458263062208-tw36mmqt'
data_path: 'gs://dataproc-staging-us-central1-458263062208-tw36mmqt/notebooks/jupyter/jupyter/Big Data Class Notebooks/Project/Project2/Project_5_steps/cleaned_data/application_record.csv'
credit_data_path: 'gs://dataproc-staging-us-central1-458263062208-tw36mmqt/notebooks/jupyter/jupyter/Big Data Class Notebooks/Project/Project2/Project_5_steps/cleaned_data/credit_record.csv'
cleaned_data_path: 'gs://dataproc-staging-us-central1-458263062208-tw36mmqt/notebooks/jupyter/jupyter/Big Data Class Notebooks/Project/Project2/Project_5_steps/cleaned_data/'
output_path: 'gs://dataproc-staging-us-central1-458263062208-tw36mmqt/notebooks/jupyter/jupyter/Big Data Class Notebooks/Project/Project2/Project_5_steps/output/'
spark:
  shuffle_partitions: 200
  executor_memory: '4g'
  executor_cores: 2
mysql_config:
  host: '34.122.208.22'
  user: 'root'
  password: 'BigData@12345'
  database: 'loan_data'
  table_name: 'credit_record'
